# Generated by Django 5.2.16 on 2026-08-23 15:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skill_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Уникальный идентификатор навыка.', primary_key=True, serialize=False, verbose_name='ID навыка')),
                ('name', models.CharField(help_text='Название навыка.', max_length=50, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
                'db_table': 'skills',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('spec_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Уникальный идентификатор специализации.', primary_key=True, serialize=False, verbose_name='ID специализации')),
                ('name', models.CharField(help_text='Название специализации.', max_length=50, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Специализация',
                'verbose_name_plural': 'Специализации',
                'db_table': 'specialization',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи.', verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время последнего изменения записи.', verbose_name='Обновлено')),
                ('username', models.CharField(blank=True, max_length=127, null=True, unique=True)),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Уникальный идентификатор.', primary_key=True, serialize=False, verbose_name='ID пользователя')),
                ('role', models.CharField(choices=[('user', 'Пользователь'), ('moderator', 'Модератор'), ('admin', 'Администратор')], default='user', help_text='Роль пользователя в системе.', max_length=20, verbose_name='Роль')),
                ('projects_relation', models.CharField(choices=[('employer', 'Наниматель'), ('worker', 'Работник')], default='worker', help_text='Роль по отношению к проектам (наниматель или исполнитель).', verbose_name='Роль в проектах')),
                ('email', models.EmailField(help_text='Действующий и уникальный адрес электронной почты, используемый для входа.', max_length=254, unique=True, verbose_name='Электронная почта')),
                ('new_email', models.EmailField(blank=True, default='', help_text='Действующий и уникальный адрес электронной почты, используемый для входа.', max_length=254, verbose_name='Новая электронная почта')),
                ('is_agreed_to_terms', models.BooleanField(default=False, help_text='Пользователь согласился с условиями использования.', verbose_name='Согласие с условиями')),
                ('onboarding_completed', models.BooleanField(default=False, help_text='Пользователь заполнил форму знакомства.', verbose_name='Онбординг завершен')),
                ('first_name', models.CharField(verbose_name='Имя')),
                ('last_name', models.CharField(verbose_name='Фамилия')),
                ('additional_contact', models.CharField(blank=True, default='', max_length=50, verbose_name='Дополнительный контакт')),
                ('country', models.CharField(blank=True, default='', max_length=70, verbose_name='Страна')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='Город')),
                ('soft_skills', models.TextField(blank=True, default='', verbose_name='Личные качества')),
                ('about_me', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('avatar_url', models.URLField(blank=True, default='', verbose_name='URL аватара')),
                ('rating', models.PositiveIntegerField(default=0, help_text='Сумма лайков ко всем вопросам и ответам пользователя', verbose_name='Рейтинг пользователя')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'users',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.ForeignKey(help_text='Навык пользователя.', on_delete=django.db.models.deletion.PROTECT, related_name='user_skills', to='users.skill', verbose_name='Навык')),
                ('user', models.ForeignKey(help_text='Пользователь, которому назначен навык.', on_delete=django.db.models.deletion.PROTECT, related_name='user_skills', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Навык пользователя',
                'verbose_name_plural': 'Навыки пользователя',
                'db_table': 'user_skills',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='users', through='users.UserSkill', to='users.skill', verbose_name='Навыки'),
        ),
        migrations.CreateModel(
            name='UserSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.ForeignKey(help_text='Специализация пользователя.', on_delete=django.db.models.deletion.CASCADE, related_name='user_specializations', to='users.specialization', verbose_name='Специализация')),
                ('user', models.ForeignKey(help_text='Пользователь, которому назначена специализация.', on_delete=django.db.models.deletion.CASCADE, related_name='user_specializations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Специализация пользователя',
                'verbose_name_plural': 'Специализации пользователя',
                'db_table': 'user_specialization',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='specializations',
            field=models.ManyToManyField(blank=True, related_name='users', through='users.UserSpecialization', to='users.specialization', verbose_name='Специализации'),
        ),
        migrations.CreateModel(
            name='UserWorkFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(help_text='Пользователь, которому назначен формат работы.', on_delete=django.db.models.deletion.PROTECT, related_name='user_workformat', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('workformat', models.ForeignKey(help_text='Формат работы пользователя.', on_delete=django.db.models.deletion.PROTECT, related_name='user_workformats', to='projects.workformat', verbose_name='Формат работы')),
            ],
            options={
                'verbose_name': 'Формат работы пользователя',
                'verbose_name_plural': 'Форматы работы пользователя.',
                'db_table': 'user_workformat',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='workformats',
            field=models.ManyToManyField(blank=True, related_name='users', through='users.UserWorkFormat', to='projects.workformat', verbose_name='Формат работы'),
        ),
        migrations.CreateModel(
            name='UserExperience',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи.', verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время последнего изменения записи.', verbose_name='Обновлено')),
                ('exp_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Уникальный идентификатор.', primary_key=True, serialize=False, verbose_name='ID записи опыта пользователя')),
                ('company', models.CharField(help_text='Название организации.', max_length=127, verbose_name='Компания')),
                ('position', models.CharField(help_text='Занимаемая должность.', max_length=127, verbose_name='Должность')),
                ('responsibilities', models.TextField(blank=True, help_text='Описание задач и достижений.', verbose_name='Обязанности')),
                ('start_date', models.DateField(verbose_name='Дата начала работы')),
                ('end_date', models.DateField(blank=True, help_text='Оставьте пустым, если работаете здесь по настоящее время.', null=True, verbose_name='Дата окончания работы')),
                ('user', models.ForeignKey(help_text='Пользователь, опыт которого описывается.', on_delete=django.db.models.deletion.PROTECT, related_name='experiences', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Опыт работы',
                'verbose_name_plural': 'Опыт работы',
                'ordering': ('-start_date',),
                'indexes': [models.Index(fields=['user', '-start_date'], name='users_usere_user_id_0a8785_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи.', verbose_name='Создано')),
                ('employer', models.ForeignKey(db_column='employer_id', on_delete=django.db.models.deletion.RESTRICT, related_name='liked_workers', to=settings.AUTH_USER_MODEL, verbose_name='Автор лайка')),
                ('worker', models.ForeignKey(db_column='worker_id', on_delete=django.db.models.deletion.RESTRICT, related_name='employers_likes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, которому поставили лайк')),
            ],
            options={
                'verbose_name': 'Лайк пользователя',
                'verbose_name_plural': 'Лайки пользователя',
                'db_table': 'user_likes',
                'indexes': [models.Index(fields=['created_at'], name='user_likes_created_0ad439_idx')],
                'constraints': [models.UniqueConstraint(fields=('employer', 'worker'), name='unique_like_employer_worker')],
            },
        ),
        migrations.AddIndex(
            model_name='userskill',
            index=models.Index(fields=['skill', 'user'], name='user_skills_skill_i_a79f10_idx'),
        ),
        migrations.AddConstraint(
            model_name='userskill',
            constraint=models.UniqueConstraint(fields=('user', 'skill'), name='unique_user_skill'),
        ),
        migrations.AddIndex(
            model_name='userspecialization',
            index=models.Index(fields=['specialization', 'user'], name='user_specia_special_11019a_idx'),
        ),
        migrations.AddConstraint(
            model_name='userspecialization',
            constraint=models.UniqueConstraint(fields=('user', 'specialization'), name='unique_user_specialization'),
        ),
        migrations.AddIndex(
            model_name='userworkformat',
            index=models.Index(fields=['workformat', 'user'], name='user_workfo_workfor_5a7e1c_idx'),
        ),
        migrations.AddConstraint(
            model_name='userworkformat',
            constraint=models.UniqueConstraint(fields=('user', 'workformat'), name='unique_user_workformat'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('new_email', ''), _negated=True), fields=('new_email',), name='unique_not_empty_new_email'),
        ),
    ]
