# Generated by Django 4.2.30 on 2026-05-12 18:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import users.models.users
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('create_date_time', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания бизнес-сущности.', verbose_name='Дата и время создания')),
                ('update_date_time', models.DateTimeField(auto_now=True, help_text='Дата и время обновления бизнес-сущности.', verbose_name='Дата и время обновления')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Уникальный идентификатор.', primary_key=True, serialize=False, verbose_name='ID пользователя')),
                ('role', models.CharField(choices=[('user', 'Пользователь'), ('moderator', 'Модератор'), ('admin', 'Администратор')], default='user', help_text='Роль пользователя в системе.', max_length=20, verbose_name='Роль')),
                ('email', models.EmailField(help_text='Действующий и уникальный адрес электронной почты, используемый для входа.', max_length=254, unique=True, verbose_name='Электронная почта')),
                ('is_staff', models.BooleanField(default=False, help_text='Отмечает, может ли пользователь входить в админку.', verbose_name='Доступ в админку')),
                ('is_active', models.BooleanField(default=True, help_text='Отмечает активного пользователя.', verbose_name='Активен')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, help_text='Дата и время регистрации пользователя.', verbose_name='Дата регистрации')),
                ('is_email_confirmed', models.BooleanField(default=False, help_text='Отмечает, подтверждён ли основной email пользователя.', verbose_name='Email подтверждён')),
                ('new_email', models.EmailField(blank=True, default='', help_text='Действующий и уникальный адрес электронной почты, используемый для входа.', max_length=254, verbose_name='Новая электронная почта')),
                ('password', models.CharField(db_column='password_hash', help_text='Хэш пароля пользователя.', max_length=128, verbose_name='Хэш пароля')),
                ('is_password_confirmed', models.BooleanField(default=False, help_text='Отмечает, подтверждён ли пароль пользователя.', verbose_name='Пароль подтверждён')),
                ('name', models.CharField(help_text='Введите имя (только буквы кириллицы или латиницы).', max_length=35, validators=[django.core.validators.MinLengthValidator(2, message='Имя не может быть короче 2 символов(а)'), django.core.validators.RegexValidator(message='Допускаются только буквы кириллицы или латиницы.', regex='^[A-Za-zА-Яа-яЁё]+$')], verbose_name='Имя')),
                ('surname', models.CharField(help_text='Введите фамилию (только буквы кириллицы или латиницы).', max_length=64, validators=[django.core.validators.MinLengthValidator(2, message='Фамилия не может быть короче 2 символов(а)'), django.core.validators.RegexValidator(message='Допускаются только буквы кириллицы или латиницы.', regex='^[A-Za-zА-Яа-яЁё]+$')], verbose_name='Фамилия')),
                ('is_agreed_to_terms', models.BooleanField(default=False, help_text='Пользователь согласился с условиями использования.', verbose_name='Согласие с условиями')),
                ('phone_number', models.CharField(blank=True, default='', max_length=20, validators=[django.core.validators.RegexValidator(message='Телефон должен начинаться с + и содержать от 10 до 20 цифр.', regex='^\\+\\d{10,20}$')], verbose_name='Номер телефона')),
                ('additional_contact', models.CharField(blank=True, default='', max_length=50, verbose_name='Дополнительный контакт')),
                ('country', models.CharField(blank=True, default='', max_length=70, verbose_name='Страна')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='Город')),
                ('about_me', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('avatar_url', models.URLField(blank=True, default='', verbose_name='URL аватара')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'users',
                'ordering': ('-create_date_time',),
            },
            managers=[
                ('objects', users.models.users.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='OauthProvider',
            fields=[
                ('provider_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Уникальный идентификатор провайдера.', primary_key=True, serialize=False, verbose_name='ID провайдера')),
                ('name', models.CharField(help_text='Название провайдера.', max_length=20, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'OAuth-провайдер',
                'verbose_name_plural': 'OAuth-провайдеры',
                'db_table': 'oauth_provider',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skill_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Уникальный идентификатор навыка.', primary_key=True, serialize=False, verbose_name='ID навыка')),
                ('name', models.CharField(help_text='Название навыка.', max_length=50, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
                'db_table': 'skills',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('spec_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Уникальный идентификатор специализации.', primary_key=True, serialize=False, verbose_name='ID специализации')),
                ('name', models.CharField(help_text='Название специализации.', max_length=50, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Специализация',
                'verbose_name_plural': 'Специализации',
                'db_table': 'specialization',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='UserSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.ForeignKey(help_text='Специализация пользователя.', on_delete=django.db.models.deletion.CASCADE, related_name='user_specializations', to='users.specialization', verbose_name='Специализация')),
                ('user', models.ForeignKey(help_text='Пользователь, которому назначена специализация.', on_delete=django.db.models.deletion.CASCADE, related_name='user_specializations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Специализация пользователя',
                'verbose_name_plural': 'Специализации пользователей',
                'db_table': 'user_specialization',
            },
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.ForeignKey(help_text='Навык пользователя.', on_delete=django.db.models.deletion.PROTECT, related_name='user_skills', to='users.skill', verbose_name='Навык')),
                ('user', models.ForeignKey(help_text='Пользователь, которому назначен навык.', on_delete=django.db.models.deletion.PROTECT, related_name='user_skills', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Навык пользователя',
                'verbose_name_plural': 'Навыки пользователей',
                'db_table': 'user_skills',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='provider',
            field=models.ForeignKey(blank=True, help_text='OAuth-провайдер пользователя.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='users.oauthprovider', verbose_name='OAuth-провайдер'),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='users', through='users.UserSkill', to='users.skill', verbose_name='Навыки'),
        ),
        migrations.AddField(
            model_name='user',
            name='specializations',
            field=models.ManyToManyField(blank=True, related_name='users', through='users.UserSpecialization', to='users.specialization', verbose_name='Специализации'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddConstraint(
            model_name='userspecialization',
            constraint=models.UniqueConstraint(fields=('user', 'specialization'), name='unique_user_specialization'),
        ),
        migrations.AddConstraint(
            model_name='userskill',
            constraint=models.UniqueConstraint(fields=('user', 'skill'), name='unique_user_skill'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('new_email', ''), _negated=True), fields=('new_email',), name='unique_not_empty_new_email'),
        ),
    ]
