# Generated by Django 4.2.30 on 2026-05-31 14:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import projects.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи.', verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время последнего изменения записи.', verbose_name='Обновлено')),
                ('project_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор проекта')),
                ('title', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(limit_value=10, message='Название должно быть не короче 10 символов.'), django.core.validators.MaxLengthValidator(limit_value=50, message='Название не должно превышать 50 символов.')], verbose_name='Название проекта')),
                ('short_desc', models.CharField(max_length=500, validators=[django.core.validators.MinLengthValidator(limit_value=20, message='Краткое описание проекта должно быть не короче 20 символов.'), django.core.validators.MaxLengthValidator(limit_value=50, message='Краткое описание проекта не должно превышать 500 символов.')], verbose_name='Краткое описание проекта')),
                ('full_desc', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=5000, message='Полное описание не должно превышать 5000 символов.')], verbose_name='Полное описание проекта')),
                ('location', models.CharField(max_length=100, validators=[projects.validators.validate_location], verbose_name='Локация проекта')),
                ('start_date', models.DateField(help_text='Если не указана — подставляется текущая дата.', verbose_name='Дата начала проекта')),
                ('end_date', models.DateField(verbose_name='Дата окончания проекта')),
                ('status_project', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован'), ('recruiting_closed', 'Набор закрыт'), ('archived', 'Архив'), ('blocked', 'Заблокирован')], default='draft', help_text='draft → published: публикация.Из published в draft запрещено.', max_length=20, verbose_name='Статус проекта')),
                ('published_at', models.DateTimeField(blank=True, editable=False, help_text='Заполняется при первом переходе draft → published. Не меняется при републикации.', null=True, verbose_name='Дата первой публикации')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата лайка')),
            ],
            options={
                'verbose_name': 'Лайк проекта',
                'verbose_name_plural': 'Лайки проектов',
                'db_table': 'project_likes',
            },
        ),
        migrations.CreateModel(
            name='ProjectParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_participant', models.CharField(choices=[('author', 'Автор'), ('member', 'Участник')], max_length=20, verbose_name='Статус участника')),
            ],
            options={
                'verbose_name': 'Участник проекта',
                'verbose_name_plural': 'Участники проекта',
                'db_table': 'project_participant',
            },
        ),
        migrations.CreateModel(
            name='WorkFormat',
            fields=[
                ('format_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор формата работы')),
                ('name', models.CharField(help_text='Пример: Удалённо, Гибрид, В офисе', max_length=50, unique=True, verbose_name='Название формата работы')),
            ],
            options={
                'verbose_name': 'Формат работы',
                'verbose_name_plural': 'Форматы работы',
                'db_table': 'work_format',
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('response_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор отклика')),
                ('initiator_type', models.CharField(choices=[('applicant', 'Отклик соискателя'), ('author', 'Приглашение от автора')], max_length=20, verbose_name='Инициатор')),
                ('status_resp', models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Одобрен'), ('rejected', 'Отклонён'), ('withdrawn', 'Отозван')], default='pending', max_length=20, verbose_name='Статус отклика')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.RESTRICT, related_name='responses', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Отклик',
                'verbose_name_plural': 'Отклики',
                'db_table': 'response',
            },
        ),
    ]
