# Generated by Django 5.2.16 on 2026-08-22 19:53

import datetime
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи.', verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время последнего изменения записи.', verbose_name='Обновлено')),
                ('project_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор проекта')),
                ('title', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Название проекта')),
                ('short_desc', models.CharField(max_length=500, validators=[django.core.validators.MinLengthValidator(20)], verbose_name='Краткое описание проекта')),
                ('full_desc', models.TextField(max_length=5000, validators=[django.core.validators.MinLengthValidator(20)], verbose_name='Полное описание проекта')),
                ('location', models.CharField(max_length=100, verbose_name='Местоположение')),
                ('telegram_contact', models.CharField(blank=True, default='', help_text='Имя пользователя Telegram (например, @username)', max_length=50, verbose_name='Telegram для связи')),
                ('start_date', models.DateField(blank=True, default=datetime.date.today, help_text='Если не указана - подставляется текущая дата.', verbose_name='Дата начала проекта')),
                ('end_date', models.DateField(verbose_name='Дата окончания проекта')),
                ('status_project', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован'), ('recruiting_closed', 'Набор закрыт'), ('archived', 'Архив'), ('blocked', 'Заблокирован')], default='draft', max_length=20, verbose_name='Статус проекта')),
                ('published_at', models.DateTimeField(blank=True, editable=False, help_text='Заполняется при первом переходе черновик → опубликовано. Не меняется при републикации.', null=True, verbose_name='Дата первой публикации')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'db_table': 'projects',
                'ordering': ('-published_at',),
            },
        ),
        migrations.CreateModel(
            name='ProjectFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи.', verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Избранное проекта',
                'verbose_name_plural': 'Избранное проектов',
                'db_table': 'project_favorites',
            },
        ),
        migrations.CreateModel(
            name='ProjectLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи.', verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Лайк проекта',
                'verbose_name_plural': 'Лайки проектов',
                'db_table': 'project_likes',
            },
        ),
        migrations.CreateModel(
            name='ProjectParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_participant', models.CharField(choices=[('author', 'Автор'), ('member', 'Участник')], max_length=20, verbose_name='Статус участника')),
            ],
            options={
                'verbose_name': 'Участник проекта',
                'verbose_name_plural': 'Участники проекта',
                'db_table': 'project_participant',
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи.', verbose_name='Создано')),
                ('response_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор отклика')),
                ('initiator_type', models.CharField(choices=[('applicant', 'Отклик соискателя'), ('author', 'Приглашение от автора')], max_length=20, verbose_name='Инициатор')),
                ('status_resp', models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Одобрен'), ('rejected', 'Отклонён'), ('withdrawn', 'Отозван')], default='pending', max_length=20, verbose_name='Статус отклика')),
            ],
            options={
                'verbose_name': 'Отклик',
                'verbose_name_plural': 'Отклики',
                'db_table': 'response',
            },
        ),
        migrations.CreateModel(
            name='WorkFormat',
            fields=[
                ('format_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор формата работы')),
                ('name', models.CharField(help_text='Пример: Удалённо, Гибрид, В офисе', max_length=50, unique=True, verbose_name='Название формата работы')),
            ],
            options={
                'verbose_name': 'Формат работы',
                'verbose_name_plural': 'Форматы работы',
                'db_table': 'work_format',
            },
        ),
    ]
