# Generated by Django 5.2.16 on 2026-08-23 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Автор проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(db_table='project_skills', related_name='projects', to='users.skill', verbose_name='Навыки для проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='specializations',
            field=models.ManyToManyField(db_table='project_specializations', related_name='projects', to='users.specialization', verbose_name='Специализации (роли в проекте)'),
        ),
        migrations.AddField(
            model_name='projectfavorite',
            name='project',
            field=models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.RESTRICT, related_name='favorites', to='projects.project', verbose_name='Проект'),
        ),
        migrations.AddField(
            model_name='projectfavorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_favorites', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='projectlike',
            name='project',
            field=models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.RESTRICT, related_name='likes', to='projects.project', verbose_name='Проект'),
        ),
        migrations.AddField(
            model_name='projectlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_likes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='projectparticipant',
            name='project',
            field=models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.RESTRICT, related_name='participants', to='projects.project', verbose_name='Проект'),
        ),
        migrations.AddField(
            model_name='projectparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_participations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='response',
            name='project',
            field=models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.RESTRICT, related_name='responses', to='projects.project', verbose_name='Проект'),
        ),
        migrations.AddField(
            model_name='response',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_format',
            field=models.ManyToManyField(db_table='project_formats', related_name='projects', to='projects.workformat', verbose_name='Формат работы'),
        ),
        migrations.AddConstraint(
            model_name='projectfavorite',
            constraint=models.UniqueConstraint(fields=('user', 'project'), name='unique_user_project_favorite'),
        ),
        migrations.AddIndex(
            model_name='projectlike',
            index=models.Index(fields=['created_at'], name='project_lik_created_a39d64_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectlike',
            constraint=models.UniqueConstraint(fields=('user', 'project'), name='unique_user_project_like'),
        ),
        migrations.AddConstraint(
            model_name='projectparticipant',
            constraint=models.UniqueConstraint(fields=('project', 'user'), name='unique_project_participant'),
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['status_resp'], name='response_status__388d4b_idx'),
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['created_at'], name='response_created_63a05e_idx'),
        ),
        migrations.AddConstraint(
            model_name='response',
            constraint=models.UniqueConstraint(fields=('project', 'user'), name='unique_response_per_project_user'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('author', 'title'), name='uniq_project_title_for_author'),
        ),
    ]
