
# ========================= РЕГИСТРАЦИЯ И АВТОРИЗАЦИЯ ======================

# @name R1. Регистрация нового пользователя
POST http://127.0.0.1:8000/api/v1/user/auth/registration/
Content-Type: application/json

{
  "email": "mos-41@yandex.ru",
  "first_name": "Олег",
  "last_name": "Миcхожев",
  "password": "CodeUnity123!"
}
###

# @name R2. Регистрация второго нового пользователя
POST http://127.0.0.1:8000/api/v1/user/auth/registration/
Content-Type: application/json

{
  "email": "omiskhozhev@gmail.com",
  "first_name": "Oleg",
  "last_name": "Miskhozhev",
  "password": "CodeUnity123!"
}
###

# @name R3. Регистрация третьего нового пользователя
POST http://127.0.0.1:8000/api/v1/user/auth/registration/
Content-Type: application/json

{
  "email": "omiskhozhev@mail.com",
  "first_name": "Иван",
  "last_name": "Иванов",
  "password": "CodeUnity123!"
}
###

# @name R4. Подтверждение регистрации (Верификация Email)
POST http://127.0.0.1:8000/api/v1/user/auth/registration/verify-email/
Content-Type: application/json

{
  "key": "MQ:1wt9SC:a6ASPPJGiLg-_tCsCaVcdFhqZUD1HlTcJXtVOmxkI3Y"
}
###

# @name R5. Подтверждение регистрации третьего пользователя (Верификация Email)
POST http://127.0.0.1:8000/api/v1/user/auth/registration/verify-email/
Content-Type: application/json

{
  "key": "Mw:1wtKTO:o2xrjoiGqZzzLe_CoivAlBnYntY7VvNP7LNxut2A488"
}
###

# @name R6. Авторизация (Вход и сохранение токенов)
POST http://127.0.0.1:8000/api/v1/user/auth/login/
Content-Type: application/json

{
  "email": "mos-41@yandex.ru",
  "password": "CodeUnity123!"
}

> {%
    // Скрипт сохраняет оба токена в глобальную память IDE
    client.global.set("access", response.body.access);
    client.global.set("refresh", response.body.refresh);
%}
###

# @name R7. Сброс забытого пароля
POST http://127.0.0.1:8000/api/v1/user/auth/password/reset/
Content-Type: application/json

{
  "email": "omiskhozhev@gmail.com"
}
###

# @name R8. Подтверждение сброса и установка нового пароля
POST http://127.0.0.1:8000/api/v1/user/auth/password/reset/confirm/
Content-Type: application/json

{
  "uid": "b435b7b13d5446658b19fba0fc545002",
  "token": "dd2lg9-2888c81be893dcd8b33d86e58c8bde71",
  "new_password": "CodeUnity123!!"
}
###

# @name R9. Авторизация (Вход и сохранение токенов) для второго пользователя
POST http://127.0.0.1:8000/api/v1/user/auth/login/
Content-Type: application/json

{
  "email": "omiskhozhev@gmail.com",
  "password": "CodeUnity123!!"
}

> {%
    client.global.set("access2", response.body.access);
    client.global.set("refresh2", response.body.refresh);
%}
###

# @name R10. Авторизация (Вход и сохранение токенов) для третьего пользователя
POST http://127.0.0.1:8000/api/v1/user/auth/login/
Content-Type: application/json

{
  "email": "omiskhozhev@mail.com",
  "password": "CodeUnity123!"
}

> {%
    client.global.set("access3", response.body.access);
    client.global.set("refresh3", response.body.refresh);
%}
###

# ============== РЕГИСТРАЦИЯ И АВТОРИЗАЦИЯ ЧЕРЕЗ ПРОВАЙДЕРА================

# @name SR1. Запрос ссылки для аторизации через Google
GET http://127.0.0.1:8000/api/v1/user/auth/google/url/
Accept: application/json
###

# ================================ ПРОФИЛЬ ================================

# @name P1. Просмотр профиля (С ТОКЕНОМ)
GET http://127.0.0.1:8000/api/v1/user/profile/me/
Authorization: Bearer {{access}}
Accept: application/json
###

# @name P2. Просмотр профиля (БЕЗ ТОКЕНА — проверка 401)
# @no-cookie-jar
GET http://127.0.0.1:8000/api/v1/user/profile/me/
Accept: application/json
###

# @name P3. Редактирование профиля (С ТОКЕНОМ)
PATCH http://127.0.0.1:8000/api/v1/user/profile/me/
Authorization: Bearer {{access}}
Content-Type: application/json

{
  "first_name": "Олег",
  "last_name": "Мисхожев"
}
###

# @name P4. Редактирование профиля (БЕЗ ТОКЕНА — проверка 401)
# @no-cookie-jar
PATCH http://127.0.0.1:8000/api/v1/user/profile/me/
Content-Type: application/json

{
  "first_name": "Олег"
}
###

# @name P5. Смена projects_relation для второго пользвателя (для создания им проектов)
PATCH http://127.0.0.1:8000/api/v1/user/profile/me/
Authorization: Bearer {{access2}}
Content-Type: application/json

{
  "projects_relation": "employer"
}
###

# @name P6. Создание опыта для третьего пользвателя
POST http://127.0.0.1:8000/api/v1/user/profile/me/experience/
Authorization: Bearer {{access3}}
Content-Type: application/json

{
  "company": "Yandex",
  "position": "Developer",
  "responsibilities": "Create RESTful API backend",
  "start_date": "2025-09-01"
}
###

# ====================== СПИСКИ ПРОФИЛЕЙ ================================

# @name LP1. Просмотр списка профилей вторым пользвателем
GET http://127.0.0.1:8000/api/v1/user/profile/
Authorization: Bearer {{access2}}
Content-Type: application/json
###

# @name LP2. Добавление профиля в избранное вторым пользвателем
POST http://127.0.0.1:8000/api/v1/user/profile/ced4c880-33b0-4959-8863-2f6329b1c568/like/
Authorization: Bearer {{access2}}
Content-Type: application/json
###

# @name LP3. Просмотр списка избранных профилей вторым пользвателем
GET http://127.0.0.1:8000/api/v1/user/profile/
    ?favourites=true
Authorization: Bearer {{access2}}
Content-Type: application/json
###

# @name LP4. Просмотр списка профилей с сортировкой по популярности вторым пользвателем
GET http://127.0.0.1:8000/api/v1/user/profile/
    ?sort_by=popularity
Authorization: Bearer {{access2}}
Content-Type: application/json
###

# @name LP5. Просмотр списка c фильтрацией по скиллам вторым пользвателем
GET http://127.0.0.1:8000/api/v1/user/profile/
    ?skill_ids=acd223f8-4553-4912-8d5e-a416da52ba93,dc17bc6c-2123-4633-be9b-d3241a64bd8d
    &sort_by=relevance
Authorization: Bearer {{access2}}
Content-Type: application/json
###

# ============================== ПРОЕКТЫ ===============================

# @name PR1. Создать проект
POST http://127.0.0.1:8000/api/v1/projects/
Authorization: Bearer {{access2}}
Content-Type: application/json

{
  "title": "StarWars new",
  "short_desc": "Dark and Light are fighting",
  "location": "Universe",
  "end_date": "3000-08-09",
  "status_project": "published",
  "skills": [
    {
      "skill_id": "dc17bc6c-2123-4633-be9b-d3241a64bd8d"
    }
  ],
  "specializations": [
    {
      "spec_id": "3193780b-fa20-4c5a-8e82-85672f5d5bb9"
    }
  ]
}
###

# @name PR2. Создать второй проект
POST http://127.0.0.1:8000/api/v1/projects/
Authorization: Bearer {{access2}}
Content-Type: application/json

{
  "title": "Matrix new generation",
  "short_desc": "We need to out from matrix...",
  "location": "Earth",
  "end_date": "2027-08-09",
  "status_project": "published",
  "skills": [
    {
      "skill_id": "dc17bc6c-2123-4633-be9b-d3241a64bd8d"
    }
  ],
  "specializations": [
    {
      "spec_id": "3193780b-fa20-4c5a-8e82-85672f5d5bb9"
    }
  ]
}
###

# @name PR3. Просмотр списка проектов
GET http://127.0.0.1:8000/api/v1/projects/
Authorization: Bearer {{access2}}
Content-Type: application/json
###

# @name PR4. Просмотр деталей проекта
GET http://127.0.0.1:8000/api/v1/projects
    /3b3ad921-97f3-49a7-b096-43938b1219b5/
Authorization: Bearer {{access2}}
Content-Type: application/json
###

# ============================== ОТКЛИКИ ===============================

# @name R1. Приглашение пользователя на проект
POST http://127.0.0.1:8000/api/v1/projects
    /30d82112-687a-4f94-9c23-23387c1ac8d7
    /invite
    /78ad8b7f-3286-4723-b5dd-82a5bef0e08a/
Authorization: Bearer {{access2}}
Content-Type: application/json
###

# @name R2. Просмотр списка откликов
GET http://127.0.0.1:8000/api/v1/user/profile/
    ?responses=true
Authorization: Bearer {{access2}}
Content-Type: application/json
###

# @name R3. Отклик на проект
POST http://127.0.0.1:8000/api/v1/projects
    /3b3ad921-97f3-49a7-b096-43938b1219b5
    /responses/
Authorization: Bearer {{access}}
Content-Type: application/json
###

# @name R4. Одобрить отклик на проект
PATCH http://127.0.0.1:8000/api/v1/projects
    /responses
    /5c8b773e-cb75-46eb-97b5-79fbd2b07b70
    /status/
Authorization: Bearer {{access2}}
Content-Type: application/json

{
  "status": "approved"
}
###