[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "backend"
version = "0.1.0"
description = "Django backend project"
readme = "README.md"
requires-python = ">=3.12"
license = { text = "MIT" }
authors = [
    { name = "Your Name", email = "your.email@example.com" }
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.12",
    "Framework :: Django",
    "Framework :: Django :: 5.2",
]

dependencies = [
    "Django>=5.2,<6.0",
    "djangorestframework>=3.17.1,<4.0",
    "django-cors-headers>=4.4.0,<5.0",
    "psycopg[binary]>=3.1.18,<4.0",
    "gunicorn>=22.0.0,<24.0",
    "python-dotenv==1.2.2",
    "djangorestframework-simplejwt>=5.5.1",
    "dj-rest-auth[with-social]>=7.2.0",
    "django-allauth>=65.16.1",
    "drf-spectacular>=0.29.0",
    "django-filter>=25.1",
    "django-storages[s3]>=1.14.6",
    "pillow>=12.2.0",
    "django-redis>=5.4.0,<6.0.0",
    "pyahocorasick>=2.3.0,<3.0",
]

[project.scripts]
manage = "manage:main"

[tool.uv]
index-url = "https://pypi.org/simple"

[tool.hatch.build.targets.wheel]
packages = ["config"]

[tool.mypy]
python_version = "3.12"
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true

[tool.ruff]
line-length = 79
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "I", "N", "UP", "B", "A", "C4", "T20", "PT", "ARG", "RET"]

[tool.ruff.lint.flake8-quotes]
inline-quotes = "single"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "config.settings_test"
python_files = ["tests.py", "test_*.py", "*_test.py"]
addopts = "-v --tb=short --ds=config.settings_test"
testpaths = ["tests"]
filterwarnings = [
    "ignore::DeprecationWarning",
]

[dependency-groups]
dev = [
    "factory-boy>=3.3.3",
    "pytest>=9.0.3",
    "pytest-django>=4.12.0",
    "pytest-mock>=3.15.1",
    "ruff>=0.15.13",
    "mypy>=1.10.0",
    "testcontainers>=4.14.2",
]
