# Generated by Django 5.2.16 on 2026-08-22 19:53

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerImage',
            fields=[
                ('image_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор изображения')),
                ('original_name', models.CharField(max_length=255, verbose_name='Оригинальное имя файла')),
                ('file_size', models.IntegerField(verbose_name='Размер файла в байтах')),
                ('mime_type', models.CharField(max_length=100, verbose_name='Тип файла')),
                ('image_url', models.URLField(max_length=255, verbose_name='URL изображения')),
            ],
            options={
                'verbose_name': 'Изображение ответа',
                'verbose_name_plural': 'Изображения ответов',
                'db_table': 'answer_image',
            },
        ),
        migrations.CreateModel(
            name='AnswerLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата лайка')),
            ],
            options={
                'verbose_name': 'Лайк ответа',
                'verbose_name_plural': 'Лайки ответов',
                'db_table': 'answer_likes',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи.', verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время последнего изменения записи.', verbose_name='Обновлено')),
                ('question_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор вопроса')),
                ('title', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Заголовок вопроса')),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(20)], verbose_name='Полное описание вопроса')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='Опубликовано анонимно')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'db_table': 'questions',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='QuestionImage',
            fields=[
                ('image_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор изображения')),
                ('original_name', models.CharField(max_length=255, verbose_name='Оригинальное имя файла')),
                ('file_size', models.IntegerField(verbose_name='Размер файла в байтах')),
                ('mime_type', models.CharField(max_length=100, verbose_name='Тип файла')),
                ('image_url', models.URLField(max_length=255, verbose_name='URL изображения')),
            ],
            options={
                'verbose_name': 'Изображение вопроса',
                'verbose_name_plural': 'Изображения вопроса',
                'db_table': 'question_image',
            },
        ),
        migrations.CreateModel(
            name='QuestionLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата лайка')),
            ],
            options={
                'verbose_name': 'Лайк вопроса',
                'verbose_name_plural': 'Лайки вопросов',
                'db_table': 'question_likes',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор ответа')),
                ('content', models.TextField(max_length=2000, verbose_name='Текст ответа')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('parent_answer', models.ForeignKey(blank=True, db_column='parent_answer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='qna.answer', verbose_name='Родительский ответ')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'db_table': 'answers',
            },
        ),
    ]
