# Generated by Django 5.2.16 on 2026-08-23 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qna', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL, verbose_name='Автор ответа'),
        ),
        migrations.AddField(
            model_name='answerimage',
            name='answer',
            field=models.ForeignKey(db_column='answer_id', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='qna.answer', verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='answerlike',
            name='answer',
            field=models.ForeignKey(db_column='answer_id', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='qna.answer', verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='answerlike',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='answer_likes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='question',
            name='skills',
            field=models.ManyToManyField(db_table='question_tags', related_name='questions', to='users.skill', verbose_name='Навыки для вопроса'),
        ),
        migrations.AddField(
            model_name='question',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL, verbose_name='Автор вопроса'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='qna.question', verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='questionimage',
            name='question',
            field=models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='qna.question', verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='questionlike',
            name='question',
            field=models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='qna.question', verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='questionlike',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='question_likes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='answerimage',
            index=models.Index(fields=['answer'], name='answer_imag_answer__98084c_idx'),
        ),
        migrations.AddIndex(
            model_name='answerlike',
            index=models.Index(fields=['created_at'], name='answer_like_created_7c3643_idx'),
        ),
        migrations.AddConstraint(
            model_name='answerlike',
            constraint=models.UniqueConstraint(fields=('user', 'answer'), name='unique_user_answer_like'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['-created_at'], name='questions_created_fc8d7e_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['-updated_at'], name='questions_updated_b2902c_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['is_active'], name='questions_is_acti_ba6b3c_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['is_anonymous'], name='questions_is_anon_82bbfc_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['question', 'created_at'], name='answers_questio_8589af_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['user'], name='answers_user_id_45f9d4_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['parent_answer'], name='answers_parent__e4f3f1_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['-created_at'], name='answers_created_657886_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['is_active'], name='answers_is_acti_0abb26_idx'),
        ),
        migrations.AddIndex(
            model_name='questionimage',
            index=models.Index(fields=['question'], name='question_im_questio_cef760_idx'),
        ),
        migrations.AddIndex(
            model_name='questionlike',
            index=models.Index(fields=['created_at'], name='question_li_created_aad883_idx'),
        ),
        migrations.AddConstraint(
            model_name='questionlike',
            constraint=models.UniqueConstraint(fields=('user', 'question'), name='unique_user_question_like'),
        ),
    ]
