# Generated by Django 4.2.30 on 2026-05-31 14:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackForm',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи.', verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время последнего изменения записи.', verbose_name='Обновлено')),
                ('feedback_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор формы')),
                ('status', models.CharField(choices=[('Sent', 'Отправлено'), ('In progress', 'В обработке'), ('Closed', 'Закрыто')], default='Sent', max_length=50, verbose_name='Статус')),
                ('subject', models.CharField(max_length=50, verbose_name='Тема')),
                ('content', models.CharField(max_length=1000, verbose_name='Содержание')),
            ],
            options={
                'verbose_name': 'Форма обратной связи',
                'verbose_name_plural': 'Формы обратной связи',
                'db_table': 'feedback_form',
            },
        ),
        migrations.CreateModel(
            name='FeedbackImage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи.', verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время последнего изменения записи.', verbose_name='Обновлено')),
                ('feedback_image', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор изображения')),
                ('original_name', models.CharField(max_length=255, verbose_name='Оригинальное имя файла')),
                ('file_size', models.IntegerField(verbose_name='Размер файла в байтах')),
                ('mime_type', models.CharField(max_length=100, verbose_name='MIME-тип')),
                ('image_url', models.URLField(max_length=255, verbose_name='URL изображения')),
                ('feedback', models.ForeignKey(db_column='feedback_id', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='feedback.feedbackform', verbose_name='Форма')),
            ],
            options={
                'verbose_name': 'Изображение для обратной связи',
                'verbose_name_plural': 'Изображения обратной связи',
                'db_table': 'feedback_form_image',
            },
        ),
    ]
