# Generated by Django 5.2.16 on 2026-08-23 15:36

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackForm',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи.', verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время последнего изменения записи.', verbose_name='Обновлено')),
                ('feedback_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор формы')),
                ('status', models.CharField(choices=[('Sent', 'Отправлено'), ('In progress', 'В обработке'), ('Closed', 'Закрыто')], default='Sent', max_length=50, verbose_name='Статус')),
                ('subject', models.CharField(max_length=50, verbose_name='Тема')),
                ('content', models.CharField(max_length=1000, verbose_name='Содержание')),
            ],
            options={
                'verbose_name': 'Форма обратной связи',
                'verbose_name_plural': 'Формы обратной связи',
                'db_table': 'feedback_form',
            },
        ),
        migrations.CreateModel(
            name='FeedbackImage',
            fields=[
                ('image_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор изображения')),
                ('original_name', models.CharField(max_length=255, verbose_name='Оригинальное имя файла')),
                ('file_size', models.IntegerField(verbose_name='Размер файла в байтах')),
                ('mime_type', models.CharField(max_length=100, verbose_name='Тип файла')),
                ('image_url', models.URLField(max_length=255, verbose_name='URL изображения')),
            ],
            options={
                'verbose_name': 'Изображение для обратной связи',
                'verbose_name_plural': 'Изображения обратной связи',
                'db_table': 'feedback_form_image',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи.', verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время последнего изменения записи.', verbose_name='Обновлено')),
                ('review_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор отзыва')),
                ('text', models.TextField(max_length=2000, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Текст отзыва')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'db_table': 'reviews',
            },
        ),
    ]
