# Generated by Django 5.2.16 on 2026-08-22 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feedback', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackform',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='feedback_forms', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='feedbackimage',
            name='feedback',
            field=models.ForeignKey(db_column='feedback_id', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='feedback.feedbackform', verbose_name='Форма'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='feedbackform',
            index=models.Index(fields=['user'], name='feedback_fo_user_id_d071d6_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackform',
            index=models.Index(fields=['status'], name='feedback_fo_status_c3f10a_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackform',
            index=models.Index(fields=['-created_at'], name='feedback_fo_created_489579_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackimage',
            index=models.Index(fields=['feedback'], name='feedback_fo_feedbac_717fe0_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user'], name='reviews_user_id_79db63_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['-created_at'], name='reviews_created_6c5dce_idx'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_user_review', violation_error_message='Пользователь уже оставил отзыв.'),
        ),
    ]
