# Контанты моделей приложения 'qna'
MAX_TITLE_QUESTION = 150
MIN_TITLE_QUESTION = 5
MIN_DESC_QUESTION = 20
MAX_CONTENT_ANSWER = 2000
MAX_ORIGINAL_NAME = 255
MAX_MINE_TYPE = 100
MAX_IMAGE_URL = 255
MAX_LEN_TITLE = 50
# Пагинация
LIMIT_QNA_MIN = 10
LIMIT_QNA_MAX = 50
