from dj_rest_auth.views import (
    LoginView,
    LogoutView,
    PasswordChangeView,
    PasswordResetConfirmView,
    PasswordResetView,
)
from django.urls import include, path
from drf_spectacular.utils import extend_schema
from rest_framework.routers import SimpleRouter
from rest_framework_simplejwt.views import (
    TokenRefreshView,
    TokenVerifyView,
)

from users.views.auth import (
    EmailChangeView,
    GoogleAuthUrlView,
    GoogleLogin,
    MailRuAuthUrlView,
    MailRuLogin,
    YandexAuthUrlView,
    YandexLogin,
)
from users.views.profile import (
    MeExperienceViewSet,
    MeProfileView,
    ProfileLikeAPIView,
    UserAvatarAPIView,
    UserProfileListView,
    UserProfileView,
)

router = SimpleRouter()
router.register(
    r'',
    MeExperienceViewSet,
    basename='my-experience',
)

urlpatterns = [
    path(
        'auth/',
        include([
            path(
                'login/',
                extend_schema(tags=['auth'])(LoginView).as_view(),
                name='rest_login',
            ),
            path(
                'logout/',
                extend_schema(tags=['auth'])(LogoutView).as_view(),
                name='rest_logout',
            ),
            path(
                'token/refresh/',
                extend_schema(tags=['auth'])(TokenRefreshView).as_view(),
                name='token_refresh',
            ),
            path(
                'token/verify/',
                extend_schema(tags=['auth'])(TokenVerifyView).as_view(),
                name='token_verify',
            ),
            path(
                'password/change/',
                extend_schema(tags=['auth'])(PasswordChangeView).as_view(),
                name='rest_password_change',
            ),
            path(
                'password/reset/',
                extend_schema(tags=['auth'])(PasswordResetView).as_view(),
                name='rest_password_reset',
            ),
            path(
                'password/reset/confirm/',
                extend_schema(tags=['auth'])(
                    PasswordResetConfirmView,
                ).as_view(),
                name='rest_password_reset_confirm',
            ),
            path(
                'registration/',
                include('dj_rest_auth.registration.urls'),
            ),
            path(
                'google/url/',
                GoogleAuthUrlView.as_view(),
                name='google_auth_url',
            ),
            path(
                'yandex/url/',
                YandexAuthUrlView.as_view(),
                name='yandex_auth_url',
            ),
            path(
                'mailru/url/',
                MailRuAuthUrlView.as_view(),
                name='mailru_auth_url',
            ),
            path(
                'google/',
                GoogleLogin.as_view(),
                name='google_login',
            ),
            path(
                'yandex/',
                YandexLogin.as_view(),
                name='yandex_login',
            ),
            path(
                'mailru/',
                MailRuLogin.as_view(),
                name='mailru_login',
            ),
        ]),
    ),
    path(
        'profile/',
        include([
            path(
                '',
                UserProfileListView.as_view(),
                name='profile-list',
            ),
            path(
                'email-change/',
                EmailChangeView.as_view(),
                name='email-change',
            ),
            path(
                '<uuid:pk>/',
                UserProfileView.as_view(),
                name='user-profile',
            ),
            path(
                '<uuid:worker_id>/like',
                ProfileLikeAPIView.as_view(),
                name='profile-like',
            ),
            path(
                'me/',
                include([
                    path(
                        '',
                        MeProfileView.as_view(),
                        name='my-profile',
                    ),
                    path(
                        'avatar/',
                        UserAvatarAPIView.as_view(),
                        name='user-avatar',
                    ),
                    path(
                        'experience/',
                        include(router.urls),
                    ),
                ]),
            ),
        ]),
    ),
]
