name: black_style_check

on:
  pull_request:
  push:
    branches:
      - develop
      - master
      - main

jobs:
  check_style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black==25.1.0

      - name: Check style with Black
        run: python -m black --check --diff .